import KatalogOne from "./katalog-1.png"
import KatalogTwo from "./katalog-2.png"
import KatalogThree from "./katalog-3.png"
import KatalogFour from "./katalog-4.png"
import KatalogFive from "./katalog-5.png"
import KatalogSix from "./katalog-6.png"
import AksiyaButsa from "./aksiya-butsa.png"
import AksiyaGantel from "./aksiya-gantel.png"
import AksiyaSportivka from "./aksiya-sportivka.png"
import AksiyaSumka from "./aksiya-sumka.png"
import NoviyKrossovka from "./noviy-krossovka.png"
import ProductOne from "./product-1.png"
import ProductTwo from "./product-2.png"
import ProductThree from "./product-3.png"
import Poleznoe from "./poleznoe.png"
import GantelSingle from "./gantel-single.png"
import GantelSingleLittle from "./gantel-single-little.png"
import AksiyaLentaTwo from "./aksiya-lenta-two.png"
import GantelKorzina from "./gantelkorzina.png"
import SumkaKorzina from "./sumkakorzina.png"
import SportivkaKorzina from "./sportivkakorzina.png"
import QolKorzina from "./qolkorzina.png"
import Bag from "./bag.png"
import Boots from "./boots.png"
import Gantels from "./gantels.png"

export {KatalogOne,KatalogTwo,KatalogThree,KatalogFour,KatalogFive,KatalogSix,AksiyaButsa,AksiyaGantel,AksiyaSportivka,AksiyaSumka,NoviyKrossovka,ProductOne,ProductTwo,ProductThree,Poleznoe,GantelSingle,GantelSingleLittle,AksiyaLentaTwo,GantelKorzina,SumkaKorzina,SportivkaKorzina,QolKorzina,Bag,Boots,Gantels}