import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer"
import Header from "@/components/header"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sport Market",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"></meta>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet">
        </link>
      </head>
      <body className={inter.className}>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
